# Generated by Django 5.0.2 on 2024-02-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(error_messages={'blank': 'yah value hal'}, max_length=100),
        ),
    ]
